### ISSUE TITLE
Sega Genesis instrument timeout

### ISSUE THREAD

**Issue by applecuckoo** [mmontag/chip-player-js#131] opened 2023-04-06 23:41 UTC
Hi there, if you play [Green Hill Zone](https://mmontag.github.io/chip-player-js/?play=Sega%20Genesis%2FSonic%20the%20Hedgehog%2F02%20-%20Green%20Hill%20Zone.vgz) from the Genesis section and solo FM 1, it skips to the next song after 10 seconds. I believe this is a silence-related timeout, since I tried soloing FM 2 and it doesn't time out.

**Comment by mmontag** [comment] 2023-04-29 22:36
Yes, indeed you are correct. game-music-emu library uses silence detection to decide when the track ends. And this is really annoying when muting channels. 

I think some tracks do rely on this silence detection, like sound effects or short jingles (will verify).
In that case, one fix would be to disable silence detection whenever track muting is applied.
It might introduce other problems, but still better than current behavior.

- [ ] verify that GME silence detection is needed
- [ ] disable silence detection upon channel mute

**Comment by mmontag** [comment] 2023-05-01 17:37
Merged a fix - let me know if you still have this problem.

**Closed by mmontag** 2023-05-01 17:37 UTC

**Comment by mmontag** [comment] 2023-05-16 08:41
Dupe of #15
